/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/EditScreenInfo`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/components/StyledText`; params?: Router.UnknownInputParams; } | { pathname: `/components/Themed`; params?: Router.UnknownInputParams; } | { pathname: `/components/useClientOnlyValue`; params?: Router.UnknownInputParams; } | { pathname: `/components/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/cuadriculada` | `/cuadriculada`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/crear` | `/crear`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/[id]` | `/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EditScreenInfo`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ExternalLink`; params?: Router.UnknownOutputParams; } | { pathname: `/components/StyledText`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Themed`; params?: Router.UnknownOutputParams; } | { pathname: `/components/useClientOnlyValue`; params?: Router.UnknownOutputParams; } | { pathname: `/components/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/cuadriculada` | `/cuadriculada`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/crear` | `/crear`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/modal` | `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/[id]` | `/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/EditScreenInfo${`?${string}` | `#${string}` | ''}` | `/components/ExternalLink${`?${string}` | `#${string}` | ''}` | `/components/StyledText${`?${string}` | `#${string}` | ''}` | `/components/Themed${`?${string}` | `#${string}` | ''}` | `/components/useClientOnlyValue${`?${string}` | `#${string}` | ''}` | `/components/useColorScheme${`?${string}` | `#${string}` | ''}` | `/constants/Colors${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/cuadriculada${`?${string}` | `#${string}` | ''}` | `/cuadriculada${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/crear${`?${string}` | `#${string}` | ''}` | `/crear${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/modal${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/EditScreenInfo`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/components/StyledText`; params?: Router.UnknownInputParams; } | { pathname: `/components/Themed`; params?: Router.UnknownInputParams; } | { pathname: `/components/useClientOnlyValue`; params?: Router.UnknownInputParams; } | { pathname: `/components/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/cuadriculada` | `/cuadriculada`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/crear` | `/crear`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | `${'/(screens)'}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(screens)'}/[id]` | `/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
