/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/crear` | `/crear`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/cuadriculada` | `/cuadriculada`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/cuadriculada.styles` | `/cuadriculada.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/[id].styles` | `/[id].styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/crear.styles` | `/crear.styles`; params?: Router.UnknownInputParams; } | { pathname: `/components/Themed`; params?: Router.UnknownInputParams; } | { pathname: `/components/useClientOnlyValue`; params?: Router.UnknownInputParams; } | { pathname: `/components/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/[id]` | `/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/index.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/crear` | `/crear`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/cuadriculada` | `/cuadriculada`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/cuadriculada.styles` | `/cuadriculada.styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/[id].styles` | `/[id].styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/crear.styles` | `/crear.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Themed`; params?: Router.UnknownOutputParams; } | { pathname: `/components/useClientOnlyValue`; params?: Router.UnknownOutputParams; } | { pathname: `/components/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/[id]` | `/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/index.styles${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/crear${`?${string}` | `#${string}` | ''}` | `/crear${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/cuadriculada${`?${string}` | `#${string}` | ''}` | `/cuadriculada${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/cuadriculada.styles${`?${string}` | `#${string}` | ''}` | `/cuadriculada.styles${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/[id].styles${`?${string}` | `#${string}` | ''}` | `/[id].styles${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/crear.styles${`?${string}` | `#${string}` | ''}` | `/crear.styles${`?${string}` | `#${string}` | ''}` | `/components/Themed${`?${string}` | `#${string}` | ''}` | `/components/useClientOnlyValue${`?${string}` | `#${string}` | ''}` | `/components/useColorScheme${`?${string}` | `#${string}` | ''}` | `/constants/Colors${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/crear` | `/crear`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/cuadriculada` | `/cuadriculada`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/cuadriculada.styles` | `/cuadriculada.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/[id].styles` | `/[id].styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/crear.styles` | `/crear.styles`; params?: Router.UnknownInputParams; } | { pathname: `/components/Themed`; params?: Router.UnknownInputParams; } | { pathname: `/components/useClientOnlyValue`; params?: Router.UnknownInputParams; } | { pathname: `/components/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownInputParams; } | `${'/(screens)'}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(screens)'}/[id]` | `/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
